### ISSUE TITLE
Request for Updated environment.yml File due to Dependency Conflicts

### ISSUE THREAD

**Issue by yizhixiaowangba45** [jinlong17/LightDiff#8]
I have been trying to set up the LightDiff environment using the provided environment.yml file. However, I am encountering dependency conflicts.Would it be possible for you to review the current environment.yml file and update it to resolve these conflicts? Thanks.

**Comment by arsity** [comment]
@yizhixiaowangba45 Hi, I have encountered similar problems. Have you solved it?
